version: "3.9"

networks:
  micro:
    driver: bridge

volumes:
  mysql-data:

services:
  mysql:
    image: mysql:8.0
    container_name: mysql
    restart: unless-stopped
    networks:
      - micro
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: ratings_db
      MYSQL_USER: user
      MYSQL_PASSWORD: 2611210yY@
    volumes:
      - mysql-data:/var/lib/mysql

  ratings-service:
    image: ratings-service
    container_name: ratings-service
    depends_on:
      - mysql
    networks:
      - micro
    environment:
      DB_URL: jdbc:mysql://mysql:3306/ratings_db
      DB_USERNAME: user
      DB_PASSWORD: 2611210yY@
    ports:
      - "8083:8083"

  mongo:
    image: mongo:6.0
    container_name: mongo
    networks:
      - micro

  info-service:
    image: info-service
    container_name: info-service
    depends_on:
      - mongo
    networks:
      - micro
    environment:
      MONGO_URI: mongodb://mongo:27017/movies_db_cache
      API_KEY: b0af84324ea41ca39f4311c9156e94e3
    ports:
      - "8082:8082"

  redis:
    image: redis:7.0
    container_name: redis
    networks:
      - micro

  trending-service:
    image: trending-service
    container_name: top
    depends_on:
      - ratings-service
      - redis
    networks:
      - micro
    environment:
      DATA_SOURCE_URL: "http://ratings-service:8083/ratings/top"
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - "9091:9091"
